global using MAUI.Core.Enums;
global using MAUI.Core.Models;
global using MAUI.Core.Services.Dialog;
global using MAUI.Core.Services.Navigation;
global using MAUI.Core.Services.Preferences;
global using MAUI.Core.Services.Sqlite;
global using MAUI.Core.Services.Web;
global using MAUI.Core.ViewModels;
global using MAUI.Core.Views;
