global using CommunityToolkit.Mvvm.ComponentModel;
global using MAUI.Core.Services.Dialog;
global using MAUI.Core.Services.Navigation;
global using MAUI.Core.Services.Sqlite;
global using MAUI.Core.Services.Web;
global using MAUI.Core.Settings;
global using MAUI.Core.ViewModels;
global using MAUI.Core.Views;
global using System.Text.Json;
